/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "FramewinDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)

static GUI_CONST_STORAGE unsigned long _acclock[] = {
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP bmclock = {
  189, // xSize
  220, // ySize
  756, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acclock,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*
*********************************************************************************************************
*                                       ???
*********************************************************************************************************
*/
#define countof(Obj) (sizeof(Obj) / sizeof(Obj[0]))
#define DEG2RAD      (3.1415926f / 180)
#define MAG          4

/*
*********************************************************************************************************
*                                       ??
*********************************************************************************************************
*/ 
static const GUI_POINT _aNeedle[] = {
  { MAG * ( -1), MAG * (  0 ) },
  { MAG * (-1), MAG * (-50 ) },
  { MAG * (0), MAG * (-65 ) },
  { MAG * ( 1), MAG * (-50 ) },
  { MAG * ( 1), MAG * (0 ) },
};

static const GUI_POINT _aNeedle1[] = {
  { MAG * ( -2), MAG * (  0 ) },
  { MAG * (-2), MAG * (-50 ) },
  { MAG * (0), MAG * (-65 ) },
  { MAG * ( 2), MAG * (-50 ) },
  { MAG * ( 2), MAG * (0 ) },
};

static const GUI_POINT _aNeedle2[] = {
  { MAG * ( -2), MAG * (  0 ) },
  { MAG * (-2), MAG * (-40 ) },
  { MAG * (0), MAG * (-55 ) },
  { MAG * ( 2), MAG * (-40 ) },
  { MAG * ( 2), MAG * (0 ) },
};

/*
*********************************************************************************************************
*                                       ????
*********************************************************************************************************
*/ 
typedef struct {
  GUI_AUTODEV_INFO AutoDevInfo;  // Information about what has to be displayed
  GUI_POINT        aPoints[7];   // Polygon data
  float            Angle;
  
  GUI_POINT        aPoints1[7];   // Polygon data
  float            Angle1;
	
  GUI_POINT        aPoints2[7];   // Polygon data
  float            Angle2;
} PARAM;


/*
*********************************************************************************************************
*	? ? ?: _Draw
*	????: ????GUI_MEMDEV_DrawAuto???
*	?    ?:p   ????
*	? ? ?: ?
*********************************************************************************************************
*/
static void _Draw(void * p) {
	PARAM * pParam;

	pParam = (PARAM *)p;

    /* ???? ************************************************************/
	if (pParam->AutoDevInfo.DrawFixed) 
	{
		/* ?????? */
		GUI_ClearRect ( (LCD_GetXSize()- bmclock.XSize)/2, 
					    (LCD_GetYSize()- bmclock.YSize)/2, 
					    (LCD_GetXSize()- bmclock.XSize)/2+bmclock.XSize, 
					    (LCD_GetYSize()- bmclock.YSize)/2+bmclock.YSize);
 		/* ?????? */
 		GUI_DrawBitmap(&bmclock, 
 		               (LCD_GetXSize()- bmclock.XSize)/2, 
 		               (LCD_GetYSize()- bmclock.YSize)/2);
	}
	
	/* ??????? ************************************************************/
	GUI_SetColor(GUI_RED);
	GUI_AA_FillPolygon(pParam->aPoints, countof(_aNeedle), MAG * LCD_GetXSize()/2, MAG * (LCD_GetYSize()/2+17));
	
	GUI_SetColor(GUI_RED);
	GUI_AA_FillPolygon(pParam->aPoints1, countof(_aNeedle1), MAG * LCD_GetXSize()/2, MAG * (LCD_GetYSize()/2+17));
	
	GUI_SetColor(GUI_RED);
	GUI_AA_FillPolygon(pParam->aPoints2, countof(_aNeedle2), MAG * LCD_GetXSize()/2, MAG * (LCD_GetYSize()/2+17));
	
	/* ????? ************************************************************/
	if (pParam->AutoDevInfo.DrawFixed) 
	{
//		GUI_SetTextMode(GUI_TM_TRANS);
//		GUI_SetColor(GUI_BLACK);
//		GUI_SetFont(&GUI_Font24B_ASCII);
//		GUI_DispStringHCenterAt("armfly", LCD_GetXSize()/2, LCD_GetYSize()/2+30);
	}
}

/*
*********************************************************************************************************
*	? ? ?: _DemoScale
*	????: ????
*	?    ?:?
*	? ? ?: ?
*********************************************************************************************************
*/
static int iWatchFaceOriginX = 240;
static int iWatchFaceOriginY = 140;
static int iWatchFaceRadius = 100;
static char acTime[10] = {"22:03:03"};
static GUI_RECT rtTime = {140, 140, 340, 180};
static void _DemoScale(WM_MESSAGE * pMsg) 
{
	WM_HWIN hWin = pMsg->hWin;
	GUI_SetBkColor(GUI_WHITE);
	GUI_Clear();
	GUI_SetColor(GUI_RED);
	GUI_DrawCircle(iWatchFaceOriginX, iWatchFaceOriginY, iWatchFaceRadius);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(&GUI_Font8x16);
	GUI_SetFont(&GUI_FontD32);
	GUI_DispStringInRectWrap(acTime, &rtTime, GUI_TA_HCENTER, GUI_WRAPMODE_WORD);

	_CreateButton(hWin, "Applist", ID_BUTTON_0, (FRAME_WIDTH >> 1) - 150, 250, 100,  50, 0);
}
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "WatchFace", ID_FRAMEWIN_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AppList", ID_BUTTON_0, 157, 251, 135, 33, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
void _cbDialog_WatchFace(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  // USER END
  WM_HWIN hWin = pMsg->hWin;
  switch (pMsg->MsgId) {
		case WM_CREATE:
			WM_SetFocus(hWin);
			
			break;
		case WM_KEY:
      switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) { 
				case GUI_KEY_ESCAPE:
          GUI_EndDialog(hWin, 1);
          break;
				case GUI_KEY_TAB:
					WM_SetFocusOnNextChild(hWin);
					break;
       }
       break;		
		case WM_PAINT:
			 _PaintFrame();
		   _DemoScale(pMsg);
			break;
		case WM_NOTIFY_PARENT:
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch(Id) {
				case ID_BUTTON_0: // Notifications sent by 'AppList'
					switch(NCode) {
						case WM_NOTIFICATION_CLICKED:
							// USER START (Optionally insert code for reacting on notification message)
							// USER END
						break;
						case WM_NOTIFICATION_RELEASED:
							// USER START (Optionally insert code for reacting on notification message)
										/* delete this frame and go to next frame */
							_DeleteFrame();
							_CreateFrame(&_cbDialog_Applist);
							// USER END
						break;
							// USER START (Optionally insert additional code for further notification handling)
							// USER END
					}
				break;
				// USER START (Optionally insert additional code for further Ids)
				// USER END
			}
			break;
			// USER START (Optionally insert additional message handling)
			// USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateFramewin_WatchFace(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog_WatchFace, WM_HBKWIN, 0, 0);
	//_DemoScale();
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
